### PR TITLE
Get style number to increment when duplicating

### PR DESCRIPTION
**Pull request by alex94945**
@alexneigher doesn't work right yet but here's what I started

### CODE REVIEW

**Comment by alexneigher** [comment]
should do TDD for this one :) I can add some code to this PR to make it work as expected...

**Comment by alexneigher** [comment]
@alex94945 i wrote some tests to cover the basic happy path. This seems to work as expected? What case are you missing?

**Comment by alex94945** [comment]
@alexneigher missing case is as follows: say you have style w/ vendor_style_number = "abc123".

If you duplicate that, it will create "abc123(1)"
If you then duplicate "abc123(1)" it will create "abc123(2)", great!

But - if instead you click duplicate on the original ("abc123"), it will create _another_ "abc123(1)". This is incorrect. It should be "abc123(3)" as it is the 3rd duplicate.

**Comment by alex94945** [comment]
closing this for now to keep branches clean. got a reasonable stop-gap in there and will re-open on a new branch when necessary.

**Pull request closed without merging**
